// B-163 C backend — entry point, declaration emission, module assembly and
// the clang shell-out (step 1 skeleton; steps 2-3 expression/statement
// emission live in codegen_c_expr.ring).
//
// Mirrors codegen_llvm.ring::generate_llvm but the module is a single C11
// translation unit built by pure Ring string assembly — ZERO FFI during
// compilation (plan-c-backend §2.1).  The .c is written to disk and compiled
// by shelling out to `clang -std=c11 -O2 -c` (clang from PATH).
//
// Determinism: every map iteration below goes through sorted keys or fixed
// declaration order (audit #237) — the emitted .c is byte-identical across
// runs (Phase 1 hard acceptance).

use types::{Type, Effect, EffectRow, effect_kind_name}
use ast::{Span}
use hir::{HExpr, HStmt, HDecl, HParam, HProgram, HStructField, HEnumVariant,
    TraitBound, evidence_param_name, trait_bound_param_name, variant_ctor_name,
    compare_by_first, hexpr_type}
use codegen_c_ctx::{CCtx, CFnInfo, CStructInfo, CEnumInfo, CEnumVariantInfo,
    new_c_ctx, c_emit, c_raw, c_param, c_mangle_fn, c_mangle_method,
    c_line_directive, rt_use, rt_use_raw, get_or_assign_c_typeid,
    is_runtime_symbol}
use codegen_c_expr::{gen_c_expr, emit_c_stmt}
use effect_analysis::{extract_effect_names, collect_fn_callees}

// ============================================================
// generate_c — main entry point (single-file).
// c_path: the .c text output; o_path: the clang-compiled object file.
// emit_lines: #line directive toggle (--no-c-lines disables).
// ============================================================

pub fn generate_c(program: HProgram, c_path: Str, o_path: Str, emit_lines: Bool) {
    let mut ctx = new_c_ctx(emit_lines)

    // B-091: auto-boxed mut-cell def_ids (closure write-through capture).
    for did in program.boxed_vars { ctx.boxed_vars.insert(did) }
    // B-144: extern type names (RC exclusion decisions — consumed in step 7's
    // emit_drop_functions, field_rc_skip flags).
    for en in program.extern_type_names { ctx.extern_types.insert(en) }
    // program.drop_types (step 7), program.static_dicts (step 5),
    // program.derived_impls (step 5 — derived Eq/Ord/Debug/Clone methods are
    // consumed through trait dict dispatch, which is step 5): not consumed yet.

    // Built-in enums (Option/Result ctors — Option layout {i64 tag, ptr payload}).
    c_register_builtin_enums(ctx)

    // Effect scan + transitive closure (B-089 G-b) — determines evidence
    // param counts, which are part of every C prototype.
    scan_fn_effects_c(program.decls, ctx.local_fn_effects)
    scan_fn_mut_params_c(program.decls, ctx.fn_mut_params)
    compute_transitive_effect_closure_c(program.decls, ctx.local_fn_effects)

    // First pass: prototypes + registries (enum variant ctors are declared
    // AND defined here — their bodies depend on nothing but the registries).
    c_forward_declare(ctx, program.decls)

    // Struct constructors after the whole forward pass: a Ring fn sharing the
    // struct's name wins the ring_<Name> symbol regardless of declaration
    // order (the LLVM backend gets this by emitting struct ctors in pass 2,
    // after every fn was declared).
    c_declare_struct_ctors(ctx, program.decls)

    // Second pass: function bodies.
    for decl in program.decls {
        emit_c_decl(ctx, decl)
    }

    // Per-type drop functions (emit_drop_functions) are step 7.

    // C main() wrapper.
    emit_c_main_wrapper(ctx)

    // Assemble + write + compile.
    let text = assemble_c_file(ctx)
    write_file(c_path, text)

    let rc = exec_sync("clang", ["-std=c11", "-O2", "-c", c_path, "-o", o_path])
    if rc != 0 {
        eprintln("ring-c: clang failed (exit code ${rc}) compiling ${c_path} — is clang on PATH?")
        exit_process(1)
    } else {
        print("Compiled: ${o_path}")
    }
}

// ============================================================
// Module assembly
// ============================================================

fn c_preamble() -> List<Str> {
    [
        "/* Generated by `ring build --target=c` (B-163 C backend). Do not edit. */",
        "/* Value representation mirrors the LLVM backend: every Ring value is a */",
        "/* void*.  Int/Bool are tagged pointers ((v << 1) | 1, B-080); Float/Str */",
        "/* /List/... are ring_alloc'd heap objects with an [rc:u32|typeid:u32]   */",
        "/* header at ptr-8 (Perceus RC).  Runtime: ring_runtime.cpp (C ABI).     */",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <math.h>",
        "",
        "#define RING_INT(v)    ((void*)(uintptr_t)((((uint64_t)(int64_t)(v)) << 1) | 1u))",
        "#define RING_BOOL(v)   RING_INT(v)",
        "#define RING_TRUE      ((void*)(uintptr_t)3)",
        "#define RING_FALSE     ((void*)(uintptr_t)1)",
        "#define RING_UNIT      ((void*)0)",
        "#define RING_UNTAG(p)  (((int64_t)(intptr_t)(p)) >> 1)",
        "#define RING_COND(p)   ((((int64_t)(intptr_t)(p)) >> 1) & 1)",
        "/* Wrapping integer arithmetic (LLVM add/sub/mul without nsw = two's-  */",
        "/* complement wrap; C signed overflow would be UB, so wrap unsigned).  */",
        "#define RING_IADD(a,b) ((int64_t)((uint64_t)(a) + (uint64_t)(b)))",
        "#define RING_ISUB(a,b) ((int64_t)((uint64_t)(a) - (uint64_t)(b)))",
        "#define RING_IMUL(a,b) ((int64_t)((uint64_t)(a) * (uint64_t)(b)))",
        "#define RING_INEG(a)   ((int64_t)(0u - (uint64_t)(a)))",
        ""
    ]
}

fn assemble_c_file(ctx: CCtx) -> Str {
    let mut out: List<Str> = []
    for l in c_preamble() { out.push(l) }

    out.push("/* ---- runtime prototypes (ring_runtime.cpp C ABI) ---- */")
    let mut rt_names = ctx.rt_protos.keys()
    rt_names.sort()
    for n in rt_names {
        match ctx.rt_protos.get(n) {
            some(p) => out.push(p),
            none => {},
        }
    }
    out.push("")

    if ctx.globals.len() > 0 {
        out.push("/* ---- string constants (explicit-length byte arrays) & const cells ---- */")
        for g in ctx.globals { out.push(g) }
        out.push("")
    }

    if ctx.fn_protos.len() > 0 {
        out.push("/* ---- ring function prototypes ---- */")
        for p in ctx.fn_protos { out.push(p) }
        out.push("")
    }

    for d in ctx.fn_defs {
        out.push(d)
        out.push("")
    }

    out.join("\n")
}

// ============================================================
// Built-in enums — Option/Result constructors.
// Option: { i64 tag, ptr payload }, typeid 8 (RING_TYPEID_OPTION).
//   ring_Option_some is emitted here; ring_Option_none is DEFINED by
//   ring_runtime.cpp (B-104 D6 memoised none singleton) — declaration only.
// Result: same layout, first user typeid (parity with the LLVM backend's
//   register_builtin_enums → get_or_assign_typeid("Result")).
// ============================================================

fn c_register_builtin_enums(mut ctx: CCtx) {
    rt_use(ctx, "ring_alloc", 2)
    rt_use(ctx, "ring_Option_none", 0)

    // Enum registry entries — match / if-let compile against these tags and
    // layouts (register_builtin_enums parity: some=0/none=1, Ok=0/Err=1).
    let mut option_variants: Map<Str, CEnumVariantInfo> = map_new()
    option_variants.insert("some", CEnumVariantInfo { tag: 0, field_count: 1, field_names: ["value"] })
    option_variants.insert("none", CEnumVariantInfo { tag: 1, field_count: 0, field_names: [] })
    ctx.enum_types.insert("Option", CEnumInfo { variants: option_variants, max_fields: 1 })

    let mut result_variants: Map<Str, CEnumVariantInfo> = map_new()
    result_variants.insert("Ok", CEnumVariantInfo { tag: 0, field_count: 1, field_names: ["value"] })
    result_variants.insert("Err", CEnumVariantInfo { tag: 1, field_count: 1, field_names: ["value"] })
    ctx.enum_types.insert("Result", CEnumInfo { variants: result_variants, max_fields: 1 })

    // Pin Option's typeid to the runtime's fixed RING_TYPEID_OPTION (8) so
    // ANY future typeid request for "Option" (e.g. a named-construct path)
    // agrees with ring_Option_some/the runtime Option makers.
    ctx.type_to_typeid.insert("Option", 8)

    ctx.functions.insert("ring_Option_some", CFnInfo { c_name: "ring_Option_some", total_params: 1 })
    ctx.functions.insert("ring_Option_none", CFnInfo { c_name: "ring_Option_none", total_params: 0 })
    ctx.functions.insert("ring_Result_Ok", CFnInfo { c_name: "ring_Result_Ok", total_params: 1 })
    ctx.functions.insert("ring_Result_Err", CFnInfo { c_name: "ring_Result_Err", total_params: 1 })
    let mut ev1: List<Str> = []
    ctx.fn_evidence_params.insert("ring_Option_some", ev1)
    let mut ev2: List<Str> = []
    ctx.fn_evidence_params.insert("ring_Option_none", ev2)
    let mut ev3: List<Str> = []
    ctx.fn_evidence_params.insert("ring_Result_Ok", ev3)
    let mut ev4: List<Str> = []
    ctx.fn_evidence_params.insert("ring_Result_Err", ev4)

    let result_tid = get_or_assign_c_typeid(ctx, "Result")

    ctx.fn_protos.push("void* ring_Option_some(void* value);")
    ctx.fn_protos.push("void* ring_Result_Ok(void* value);")
    ctx.fn_protos.push("void* ring_Result_Err(void* value);")

    let mut some_def: List<Str> = []
    some_def.push("void* ring_Option_some(void* value) {")
    some_def.push("    void* p = ring_alloc((int64_t)(sizeof(int64_t) + sizeof(void*)), 8);")
    some_def.push("    *(int64_t*)p = 0;")
    some_def.push("    *(void**)((char*)p + sizeof(int64_t)) = value;")
    some_def.push("    return p;")
    some_def.push("}")
    ctx.fn_defs.push(some_def.join("\n"))

    let mut ok_def: List<Str> = []
    ok_def.push("void* ring_Result_Ok(void* value) {")
    ok_def.push("    void* p = ring_alloc((int64_t)(sizeof(int64_t) + sizeof(void*)), ${result_tid});")
    ok_def.push("    *(int64_t*)p = 0;")
    ok_def.push("    *(void**)((char*)p + sizeof(int64_t)) = value;")
    ok_def.push("    return p;")
    ok_def.push("}")
    ctx.fn_defs.push(ok_def.join("\n"))

    let mut err_def: List<Str> = []
    err_def.push("void* ring_Result_Err(void* value) {")
    err_def.push("    void* p = ring_alloc((int64_t)(sizeof(int64_t) + sizeof(void*)), ${result_tid});")
    err_def.push("    *(int64_t*)p = 1;")
    err_def.push("    *(void**)((char*)p + sizeof(int64_t)) = value;")
    err_def.push("    return p;")
    err_def.push("}")
    ctx.fn_defs.push(err_def.join("\n"))
}

// ============================================================
// Forward declaration pass — prototypes + registries.
// ============================================================

fn c_forward_declare(mut ctx: CCtx, decls: List<HDecl>) {
    for decl in decls {
        match decl {
            HDecl::Fn { name, params, effects, trait_bounds, .. } => {
                c_declare_fn(ctx, c_mangle_fn(name), name, params, effects, trait_bounds)
            },
            HDecl::Impl { target_type, methods, .. } => {
                for m in methods {
                    match m {
                        HDecl::Fn { name: mn, params: mp, effects: me, trait_bounds: mtb, .. } => {
                            // #177: qualified effect key matching scan_fn_effects_c.
                            c_declare_fn(ctx, c_mangle_method(target_type, mn), "${target_type}_${mn}", mp, me, mtb)
                        },
                        _ => {},
                    }
                }
            },
            HDecl::Struct { name, fields, .. } => {
                let mut fnames: List<Str> = []
                for f in fields { fnames.push(f.name) }
                ctx.struct_types.insert(name, CStructInfo { field_names: fnames })
                // The ring_<Name> constructor fn is declared AFTER the whole
                // forward pass (c_declare_struct_ctors) — fns win collisions.
            },
            HDecl::Enum { name, variants, .. } => {
                register_c_enum_info(ctx, name, variants)
                c_emit_enum_ctors(ctx, name, variants)
            },
            HDecl::Const { name, .. } => {
                // Const = zero-arg lazy getter (same scheme as the LLVM backend).
                let mangled = c_mangle_fn(name)
                if ctx.functions.contains_key(mangled) == false {
                    let c_name = if is_runtime_symbol(mangled) { "${mangled}__ring" } else { mangled }
                    ctx.functions.insert(mangled, CFnInfo { c_name: c_name, total_params: 0 })
                    let mut no_ev: List<Str> = []
                    ctx.fn_evidence_params.insert(mangled, no_ev)
                    ctx.fn_protos.push("void* ${c_name}(void);")
                }
            },
            HDecl::Test { .. } => {
                // #215: test block as a zero-arg function.
                let test_name = "ring_test_${ctx.test_fns.len()}"
                ctx.functions.insert(test_name, CFnInfo { c_name: test_name, total_params: 0 })
                let mut no_ev: List<Str> = []
                ctx.fn_evidence_params.insert(test_name, no_ev)
                ctx.fn_protos.push("void* ${test_name}(void);")
                ctx.test_fns.push(test_name)
            },
            HDecl::ModBlock { decls: md, .. } => {
                // Inline-mod decl names are already module-prefixed by the
                // checker; `::` sanitizes to `__` in c_mangle_fn.
                c_forward_declare(ctx, md)
            },
            HDecl::Effect { .. } => {},       // effect evidence structs: step 6
            HDecl::Trait { .. } => {},        // default trait methods: step 5
            HDecl::ExternFn { .. } => {},     // declared lazily at call sites
            HDecl::ExternType { .. } => {},
            HDecl::TypeAlias { .. } => {},
            HDecl::Sig { .. } => {},
        }
    }
}

// ============================================================
// Enum registration + variant constructors (ports of register_enum_info /
// forward_declare_enum_ctors / emit_enum_constructors).  Tags are assigned in
// declaration order; the value layout is { int64_t tag, void* f0, ... } —
// see codegen_c_ctx::CEnumInfo.  Constructors are declared AND defined in the
// forward pass: their bodies only need the registry + typeid, and this keeps
// the declare-time collision skip and the definition in one place.
// ============================================================

fn register_c_enum_info(mut ctx: CCtx, name: Str, variants: List<HEnumVariant>) {
    let mut max_fields = 0
    let mut variant_map: Map<Str, CEnumVariantInfo> = map_new()
    let mut tag = 0
    for v in variants {
        let fc = v.fields.len()
        if fc > max_fields {
            max_fields = fc
        }
        let fnames = match v.field_names {
            some(names) => names,
            none => {
                let mut ns: List<Str> = []
                for _j in 0..fc { ns.push("") }
                ns
            },
        }
        variant_map.insert(v.name, CEnumVariantInfo { tag: tag, field_count: fc, field_names: fnames })
        tag = tag + 1
    }
    ctx.enum_types.insert(name, CEnumInfo { variants: variant_map, max_fields: max_fields })
}

fn c_emit_enum_ctors(mut ctx: CCtx, name: Str, variants: List<HEnumVariant>) {
    let max_fields = match ctx.enum_types.get(name) {
        some(ei) => ei.max_fields,
        none => panic("C codegen: enum '${name}' not registered"),
    }
    rt_use(ctx, "ring_alloc", 2)
    let tid = get_or_assign_c_typeid(ctx, name)
    let mut tag = 0
    for v in variants {
        let key = c_mangle_fn(variant_ctor_name(name, v.name))
        let vtag = tag
        tag = tag + 1
        // First-come-wins within the forward pass (forward_declare_enum_ctors
        // skip parity) — also prevents a duplicate C definition.
        if ctx.functions.contains_key(key) {
            continue
        }
        let c_name = if is_runtime_symbol(key) { "${key}__ring" } else { key }
        ctx.functions.insert(key, CFnInfo { c_name: c_name, total_params: v.fields.len() })
        let mut no_ev: List<Str> = []
        ctx.fn_evidence_params.insert(key, no_ev)

        let mut ps: List<Str> = []
        for i in 0..v.fields.len() { ps.push("void* a${i}") }
        let params_str = if ps.len() == 0 { "void" } else { ps.join(", ") }
        ctx.fn_protos.push("void* ${c_name}(${params_str});")

        let mut def: List<Str> = []
        def.push("void* ${c_name}(${params_str}) {")
        def.push("    void* p = ring_alloc((int64_t)(sizeof(int64_t) + ${max_fields} * sizeof(void*)), ${tid});")
        def.push("    *(int64_t*)p = ${vtag};")
        for i in 0..v.fields.len() {
            def.push("    ((void**)p)[${i + 1}] = a${i};")
        }
        def.push("    return p;")
        def.push("}")
        ctx.fn_defs.push(def.join("\n"))
    }
}

// Struct constructors — declared+defined after the forward pass so that any
// Ring fn with the struct's name keeps the ring_<Name> symbol (LLVM parity:
// emit_struct_constructor's already-declared skip runs in pass 2).
fn c_declare_struct_ctors(mut ctx: CCtx, decls: List<HDecl>) {
    for decl in decls {
        match decl {
            HDecl::Struct { name, fields, .. } => {
                c_emit_struct_ctor(ctx, name, fields)
            },
            HDecl::ModBlock { decls: md, .. } => {
                c_declare_struct_ctors(ctx, md)
            },
            _ => {},
        }
    }
}

fn c_emit_struct_ctor(mut ctx: CCtx, name: Str, fields: List<HStructField>) {
    let key = c_mangle_fn(name)
    if ctx.functions.contains_key(key) {
        // A fn (or enum ctor) already owns this symbol — skip (LLVM parity).
        return
    }
    let c_name = if is_runtime_symbol(key) { "${key}__ring" } else { key }
    ctx.functions.insert(key, CFnInfo { c_name: c_name, total_params: fields.len() })
    let mut no_ev: List<Str> = []
    ctx.fn_evidence_params.insert(key, no_ev)

    rt_use(ctx, "ring_alloc", 2)
    let tid = get_or_assign_c_typeid(ctx, name)
    let mut ps: List<Str> = []
    for i in 0..fields.len() { ps.push("void* a${i}") }
    let params_str = if ps.len() == 0 { "void" } else { ps.join(", ") }
    ctx.fn_protos.push("void* ${c_name}(${params_str});")

    let mut def: List<Str> = []
    def.push("void* ${c_name}(${params_str}) {")
    def.push("    void* p = ring_alloc((int64_t)(${fields.len()} * sizeof(void*)), ${tid});")
    for i in 0..fields.len() {
        def.push("    ((void**)p)[${i}] = a${i};")
    }
    def.push("    return p;")
    def.push("}")
    ctx.fn_defs.push(def.join("\n"))
}

fn c_declare_fn(mut ctx: CCtx, mangled: Str, effect_key: Str, params: List<HParam>, effects: EffectRow, trait_bounds: List<TraitBound>) {
    // Effective effects: transitive closure result wins over the decl row.
    let effective = match ctx.local_fn_effects.get(effect_key) {
        some(e) => e,
        none => effects,
    }
    let ev_names = extract_effect_names(effective)
    let mut ev_params: List<Str> = []
    for en in ev_names { ev_params.push(evidence_param_name(en)) }
    ctx.fn_evidence_params.insert(mangled, ev_params)

    // Dedupe (multi-decl re-declaration parity with forward_declare_fn_with_name).
    if ctx.functions.contains_key(mangled) { return }

    // Symbol-collision rename: a Ring fn whose mangled name IS a runtime
    // symbol (std map_new → ring_map_new C++ shim) gets a __ring suffix.
    // All call sites resolve through CFnInfo.c_name, so this is transparent;
    // direct calls to such names route through extern_fn_to_runtime first
    // (runtime shim), matching the LLVM backend's behaviour.
    let c_name = if is_runtime_symbol(mangled) {
        "${mangled}__ring"
    } else {
        mangled
    }

    let total = params.len() + trait_bounds.len() + ev_params.len()
    ctx.functions.insert(mangled, CFnInfo { c_name: c_name, total_params: total })

    let mut ps: List<Str> = []
    for _p in params { ps.push("void*") }
    for _b in trait_bounds { ps.push("void*") }
    for _e in ev_params { ps.push("void*") }
    let params_str = if ps.len() == 0 { "void" } else { ps.join(", ") }
    ctx.fn_protos.push("void* ${c_name}(${params_str});")
}

// ============================================================
// Declaration body emission
// ============================================================

fn emit_c_decl(mut ctx: CCtx, decl: HDecl) {
    match decl {
        HDecl::Fn { name, params, effects, body, trait_bounds, span, .. } => {
            emit_c_fn_body(ctx, name, params, effects, body, trait_bounds, none, span)
        },
        HDecl::Impl { target_type, methods, .. } => {
            for m in methods {
                match m {
                    HDecl::Fn { name: mn, params: mp, effects: me, body: mb, trait_bounds: mtb, span: msp, .. } => {
                        emit_c_fn_body(ctx, mn, mp, me, mb, mtb, some(target_type), msp)
                    },
                    _ => {},
                }
            }
            // Trait dict emission for trait impls: step 5.
        },
        HDecl::Struct { .. } => {},
        HDecl::Enum { .. } => {},
        HDecl::Effect { .. } => {},
        HDecl::Test { body, span, .. } => {
            let test_name = ctx.test_fns[ctx.test_emit_idx]
            ctx.test_emit_idx = ctx.test_emit_idx + 1
            emit_c_zero_arg_fn(ctx, test_name, body, span)
        },
        HDecl::Trait { .. } => {},
        HDecl::ExternFn { .. } => {},
        HDecl::ExternType { .. } => {},
        HDecl::TypeAlias { .. } => {},
        HDecl::Const { name, init, span, .. } => {
            emit_c_const_body(ctx, name, init, span)
        },
        HDecl::ModBlock { decls: md, .. } => {
            for sub in md { emit_c_decl(ctx, sub) }
        },
        HDecl::Sig { .. } => {},
    }
}

// Per-function emission state bracket (the C analogue of LLVM entry-block
// setup in emit_fn_body).  Returns the saved named_values to restore.
fn begin_c_fn(mut ctx: CCtx, mangled: Str) -> Map<Str, Str> {
    ctx.cur_decls = []
    ctx.cur_body = []
    ctx.used_locals = set_new()
    let saved = ctx.named_values
    ctx.named_values = map_new()
    ctx.in_function = true
    ctx.current_fn_name = mangled
    ctx.indent = 1
    ctx.last_line = -1
    ctx.last_file = ""
    saved
}

fn end_c_fn(mut ctx: CCtx, mangled: Str, params_str: Str, saved: Map<Str, Str>) {
    let mut def: List<Str> = []
    def.push("void* ${mangled}(${params_str}) {")
    for d in ctx.cur_decls { def.push(d) }
    for l in ctx.cur_body { def.push(l) }
    def.push("}")
    ctx.fn_defs.push(def.join("\n"))
    ctx.named_values = saved
    ctx.in_function = false
    ctx.current_fn_name = ""
}

fn emit_c_fn_body(mut ctx: CCtx, name: Str, params: List<HParam>, effects: EffectRow, body: HExpr, trait_bounds: List<TraitBound>, impl_type: Str?, span: Span) {
    let mangled = match impl_type {
        some(t) => c_mangle_method(t, name),
        none => c_mangle_fn(name),
    }
    // Definition symbol = CFnInfo.c_name (collision-renamed when needed).
    let c_name = match ctx.functions.get(mangled) {
        some(fi) => fi.c_name,
        none => panic("C codegen: function '${mangled}' not forward-declared"),
    }

    // First definition wins (see CCtx.emitted_fns): a later decl with the
    // same mangled name (user enum shadowing a prelude type's impl) would be
    // a C redefinition error; call sites all resolve to the first symbol,
    // matching the LLVM backend's effective behaviour.
    if ctx.emitted_fns.contains(c_name) { return }
    ctx.emitted_fns.insert(c_name)

    let saved = begin_c_fn(ctx, mangled)

    // Parameters → C signature (uniform void* boxing, LLVM parity).
    let mut sig_parts: List<Str> = []
    for p in params {
        let cn = c_param(ctx, p.name)
        sig_parts.push("void* ${cn}")
    }
    for b in trait_bounds {
        let dn = trait_bound_param_name(b.type_param, b.trait_name)
        let cn = c_param(ctx, dn)
        sig_parts.push("void* ${cn}")
    }
    let effect_key = match impl_type {
        some(t) => "${t}_${name}",
        none => name,
    }
    let effective = match ctx.local_fn_effects.get(effect_key) {
        some(e) => e,
        none => effects,
    }
    for en in extract_effect_names(effective) {
        let ep = evidence_param_name(en)
        let cn = c_param(ctx, ep)
        sig_parts.push("void* ${cn}")
    }
    let params_str = if sig_parts.len() == 0 { "void" } else { sig_parts.join(", ") }

    c_line_directive(ctx, span)
    let val = gen_c_expr(ctx, body)
    c_emit(ctx, "return ${val};")

    end_c_fn(ctx, c_name, params_str, saved)
}

fn emit_c_zero_arg_fn(mut ctx: CCtx, mangled: Str, body: HExpr, span: Span) {
    let saved = begin_c_fn(ctx, mangled)
    c_line_directive(ctx, span)
    let val = gen_c_expr(ctx, body)
    c_emit(ctx, "return ${val};")
    end_c_fn(ctx, mangled, "void", saved)
}

// ============================================================
// Const bodies — port of emit_const_body (B-104 D6/D9):
//   Str const  → lazy memoised getter, interned via ring_const_intern
//   enum const → lazy memoised getter, interned via ring_unit_intern
//   other      → per-access re-evaluation (fresh scalar box per call)
// ============================================================

fn emit_c_const_body(mut ctx: CCtx, name: Str, init: HExpr, span: Span) {
    let mangled = c_mangle_fn(name)
    // Not forward-declared — skip (LLVM parity).
    if ctx.functions.contains_key(mangled) == false { return }
    let c_name = match ctx.functions.get(mangled) {
        some(fi) => fi.c_name,
        none => mangled,
    }
    let is_str_const = match hexpr_type(init) {
        Type::StrType => true,
        _ => false,
    }
    let is_enum_const = match hexpr_type(init) {
        Type::EnumType { .. } => true,
        _ => false,
    }
    if is_str_const {
        emit_c_memoised_const(ctx, c_name, init, "ring_const_intern", span)
    } else if is_enum_const {
        emit_c_memoised_const(ctx, c_name, init, "ring_unit_intern", span)
    } else {
        emit_c_zero_arg_fn(ctx, c_name, init, span)
    }
}

fn emit_c_memoised_const(mut ctx: CCtx, mangled: Str, init: HExpr, intern_fn: Str, span: Span) {
    let g = "__ring_constg_${mangled}"
    ctx.globals.push("static void* ${g} = 0;")
    rt_use(ctx, intern_fn, 1)

    let saved = begin_c_fn(ctx, mangled)
    c_line_directive(ctx, span)
    c_emit(ctx, "if (${g} == 0) {")
    ctx.indent = ctx.indent + 1
    let built = gen_c_expr(ctx, init)
    c_emit(ctx, "${g} = ${intern_fn}(${built});")
    ctx.indent = ctx.indent - 1
    c_emit(ctx, "}")
    c_emit(ctx, "return ${g};")
    end_c_fn(ctx, mangled, "void", saved)
}

// ============================================================
// C main() wrapper — parity with emit_c_main_common:
//   ring_runtime_init(argc, argv) → [drop registrations: step 7] →
//   ring_main(default evidence…) or test functions → return 0.
// Default evidence structs (B-097) are step 6 — NULL for now (the runtime
// handles io/fail without evidence).
// ============================================================

fn emit_c_main_wrapper(mut ctx: CCtx) {
    rt_use_raw(ctx, "ring_runtime_init", "void ring_runtime_init(int argc, char** argv);")
    let mut lines: List<Str> = []
    lines.push("int main(int argc, char** argv) {")
    lines.push("    ring_runtime_init(argc, argv);")
    match ctx.functions.get("ring_main") {
        some(_) => {
            let mut args: List<Str> = []
            match ctx.fn_evidence_params.get("ring_main") {
                some(evs) => {
                    for _e in evs { args.push("RING_UNIT") }
                },
                none => {},
            }
            lines.push("    ring_main(${args.join(", ")});")
        },
        none => {
            // #215: no fn main — run test functions in declaration order.
            for t in ctx.test_fns {
                lines.push("    ${t}();")
            }
        },
    }
    lines.push("    return 0;")
    lines.push("}")
    ctx.fn_defs.push(lines.join("\n"))
}

// ============================================================
// Effect scanning — verbatim ports of the codegen_llvm.ring private passes
// (scan_fn_effects / scan_fn_mut_params_llvm / compute_transitive_effect_
// closure / collect_local_names_rec).  Copied because the originals are
// module-private and codegen_llvm*.ring must stay untouched (B-163 rule:
// the LLVM backend is the differential oracle).
// ============================================================

fn scan_fn_effects_c(decls: List<HDecl>, mut local_fn_effects: Map<Str, EffectRow>) {
    for decl in decls {
        match decl {
            HDecl::Fn { name, effects, .. } => {
                if effects.effects.len() > 0 {
                    local_fn_effects.insert(name, effects)
                }
            },
            HDecl::Impl { target_type, methods, .. } => {
                for m in methods {
                    match m {
                        HDecl::Fn { name: mn, effects: me, .. } => {
                            if me.effects.len() > 0 {
                                let key = "${target_type}_${mn}"
                                local_fn_effects.insert(key, me)
                            }
                        },
                        _ => {},
                    }
                }
            },
            HDecl::ModBlock { decls: md, .. } => {
                scan_fn_effects_c(md, local_fn_effects)
            },
            _ => {},
        }
    }
}

// A value type (Int/Float/Bool/Str) is the only kind a `mut` param boxes
// into a CELL (#B-087 gap 5).
fn c_is_value_type(t: Type) -> Bool {
    match t {
        Type::IntType => true,
        Type::FloatType => true,
        Type::BoolType => true,
        Type::StrType => true,
        _ => false,
    }
}

fn mut_param_flags_c(params: List<HParam>) -> List<Bool> {
    let mut flags: List<Bool> = []
    for p in params {
        if p.name == "self" || !p.is_mutable {
            flags.push(false)
        } else {
            flags.push(c_is_value_type(p.ty))
        }
    }
    flags
}

fn scan_fn_mut_params_c(decls: List<HDecl>, mut fn_mut_params: Map<Str, List<Bool>>) {
    for decl in decls {
        match decl {
            HDecl::Fn { name, params, .. } => {
                fn_mut_params.insert(name, mut_param_flags_c(params))
            },
            HDecl::Impl { target_type, methods, .. } => {
                for m in methods {
                    match m {
                        HDecl::Fn { name: mn, params: mp, .. } => {
                            let ufcs_name = "${target_type}_${mn}"
                            fn_mut_params.insert(ufcs_name, mut_param_flags_c(mp))
                        },
                        _ => {},
                    }
                }
            },
            HDecl::ModBlock { decls: md, .. } => {
                scan_fn_mut_params_c(md, fn_mut_params)
            },
            _ => {},
        }
    }
}

fn collect_local_names_rec_c(decls: List<HDecl>, mut names: Set<Str>) {
    for decl in decls {
        match decl {
            HDecl::Fn { name, .. } => { names.insert(name) },
            HDecl::Impl { target_type, methods, .. } => {
                for m in methods {
                    match m {
                        HDecl::Fn { name: mn, .. } => { names.insert("${target_type}_${mn}") },
                        _ => {},
                    }
                }
            },
            HDecl::ModBlock { decls: md, .. } => { collect_local_names_rec_c(md, names) },
            _ => {},
        }
    }
}

fn compute_transitive_effect_closure_c(decls: List<HDecl>, mut local_fn_effects: Map<Str, EffectRow>) {
    if local_fn_effects.len() == 0 { return }
    let mut local_names: Set<Str> = set_new()
    collect_local_names_rec_c(decls, local_names)
    let mut fn_callees: Map<Str, Set<Str>> = map_new()
    collect_fn_callees(decls, local_names, fn_callees)
    let mut changed = true
    while changed {
        changed = false
        let mut sorted_callees = fn_callees.entries()
        sorted_callees.sort_by(compare_by_first)
        for entry in sorted_callees {
            let (name, callees) = entry
            let mut sorted_callee_names = callees.to_list()
            sorted_callee_names.sort()
            for callee in sorted_callee_names {
                match local_fn_effects.get(callee) {
                    some(callee_effects) => {
                        match local_fn_effects.get(name) {
                            none => {
                                let mut effs: List<Effect> = []
                                for e in callee_effects.effects { effs.push(e) }
                                local_fn_effects.insert(name, EffectRow { effects: effs, tail: none })
                                changed = true
                            },
                            some(current) => {
                                for e in callee_effects.effects {
                                    let ename = effect_kind_name(e)
                                    let mut found = false
                                    for ce in current.effects {
                                        if effect_kind_name(ce) == ename { found = true }
                                    }
                                    if found == false {
                                        current.effects.push(e)
                                        changed = true
                                    }
                                }
                            },
                        }
                    },
                    none => {},
                }
            }
        }
    }
}
